/* Generated by wayland-scanner 1.24.0 */

#ifndef HEVEL_SERVER_PROTOCOL_H
#define HEVEL_SERVER_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-server.h"

#ifdef  __cplusplus
extern "C" {
#endif

struct wl_client;
struct wl_resource;

/**
 * @page page_hevel The hevel protocol
 * @section page_ifaces_hevel Interfaces
 * - @subpage page_iface_hevel_scroll - the current positon in the infinite scrolling plane
 * @section page_copyright_hevel Copyright
 * <pre>
 *
 * lul lmao, diz 4 hevel x3 rawr
 * </pre>
 */
struct hevel_scroll;

#ifndef HEVEL_SCROLL_INTERFACE
#define HEVEL_SCROLL_INTERFACE
/**
 * @page page_iface_hevel_scroll hevel_scroll
 * @section page_iface_hevel_scroll_desc Description
 *
 * Hevel is a scrolling window manager, it has an inifnite vertical space.
 * @section page_iface_hevel_scroll_api API
 * See @ref iface_hevel_scroll.
 */
/**
 * @defgroup iface_hevel_scroll The hevel_scroll interface
 *
 * Hevel is a scrolling window manager, it has an inifnite vertical space.
 */
extern const struct wl_interface hevel_scroll_interface;
#endif

#define HEVEL_SCROLL_GET_POS 0

/**
 * @ingroup iface_hevel_scroll
 */
#define HEVEL_SCROLL_GET_POS_SINCE_VERSION 1


/**
 * @ingroup iface_hevel_scroll
 * Sends an get_pos event to the client owning the resource.
 * @param resource_ The client's resource
 */
static inline void
hevel_scroll_send_get_pos(struct wl_resource *resource_, int32_t pos)
{
	wl_resource_post_event(resource_, HEVEL_SCROLL_GET_POS, pos);
}

#ifdef  __cplusplus
}
#endif

#endif
