/* Generated by wayland-scanner 1.24.0 */

#ifndef HEVEL_CLIENT_PROTOCOL_H
#define HEVEL_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_hevel The hevel protocol
 * @section page_ifaces_hevel Interfaces
 * - @subpage page_iface_hevel_scroll - the current positon in the infinite scrolling plane
 * @section page_copyright_hevel Copyright
 * <pre>
 *
 * lul lmao, diz 4 hevel x3 rawr
 * </pre>
 */
struct hevel_scroll;

#ifndef HEVEL_SCROLL_INTERFACE
#define HEVEL_SCROLL_INTERFACE
/**
 * @page page_iface_hevel_scroll hevel_scroll
 * @section page_iface_hevel_scroll_desc Description
 *
 * Hevel is a scrolling window manager, it has an inifnite vertical space.
 * @section page_iface_hevel_scroll_api API
 * See @ref iface_hevel_scroll.
 */
/**
 * @defgroup iface_hevel_scroll The hevel_scroll interface
 *
 * Hevel is a scrolling window manager, it has an inifnite vertical space.
 */
extern const struct wl_interface hevel_scroll_interface;
#endif

/**
 * @ingroup iface_hevel_scroll
 * @struct hevel_scroll_listener
 */
struct hevel_scroll_listener {
	/**
	 */
	void (*get_pos)(void *data,
			struct hevel_scroll *hevel_scroll,
			int32_t pos);
};

/**
 * @ingroup iface_hevel_scroll
 */
static inline int
hevel_scroll_add_listener(struct hevel_scroll *hevel_scroll,
			  const struct hevel_scroll_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) hevel_scroll,
				     (void (**)(void)) listener, data);
}

/**
 * @ingroup iface_hevel_scroll
 */
#define HEVEL_SCROLL_GET_POS_SINCE_VERSION 1


/** @ingroup iface_hevel_scroll */
static inline void
hevel_scroll_set_user_data(struct hevel_scroll *hevel_scroll, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) hevel_scroll, user_data);
}

/** @ingroup iface_hevel_scroll */
static inline void *
hevel_scroll_get_user_data(struct hevel_scroll *hevel_scroll)
{
	return wl_proxy_get_user_data((struct wl_proxy *) hevel_scroll);
}

static inline uint32_t
hevel_scroll_get_version(struct hevel_scroll *hevel_scroll)
{
	return wl_proxy_get_version((struct wl_proxy *) hevel_scroll);
}

/** @ingroup iface_hevel_scroll */
static inline void
hevel_scroll_destroy(struct hevel_scroll *hevel_scroll)
{
	wl_proxy_destroy((struct wl_proxy *) hevel_scroll);
}

#ifdef  __cplusplus
}
#endif

#endif
