/* Generated by wayland-scanner 1.24.0 */

/*
 * lul lmao, diz 4 hevel x3 rawr
 */

#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include "wayland-util.h"


static const struct wl_interface *hevel_types[] = {
	NULL,
};

static const struct wl_message hevel_scroll_events[] = {
	{ "get_pos", "i", hevel_types + 0 },
};

WL_EXPORT const struct wl_interface hevel_scroll_interface = {
	"hevel_scroll", 1,
	0, NULL,
	1, hevel_scroll_events,
};

